### ISSUE TITLE
Homologação e Certificações

### ISSUE THREAD

**Issue by monikinhanx** [marcilioramos/smartnurse#2]
Marcilio, Boa tarde!

Curti muito o projeto, ainda mais agora com a vertical da Saúde tão em voga.
Mas tenho uma pergunta, pra entrar com projetos em hospitais precisam de algumas certificações e homologações (tipo Anatel, Anvisa, Inmetro, ONA, JCI e etc...).

Vc já tem isso em mente com esse projeto?

**Comment by marcilioramos** [comment]
Boa noite Moniki,

Acredito que sim Moniki, como eu trabalho em um hospital municipal irei usar nosso hospital e equipe tecnica multidisciplinar para nos assessorar nesse ponto.

Estarei pulicando esses pontos aqui, quando o projeto for se desenvolvendo.

Quanto a ANATEL o equipamento já é homologado. Acredito que a ANVISA será algo mais burocrático, pois devem existir muito requisitos para atuar com a vida humana.

**Comment by monikinhanx** [comment]
Uauuu... Mt legal! Parabéns mesmo pelo projeto!
